root: true

env:
  es2021: true
  node: true

parser: '@typescript-eslint/parser'

extends:
  - eslint:recommended
  - prettier

ignorePatterns:
  - node_modules
  - dist

rules:
  no-console:
    - error
    - allow:
        - warn
        - error
        - info

  curly:
    - error
    - all
