extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier-scss

rules:
  no-empty-source: null

  selector-class-pattern: null

  scss/dollar-variable-pattern: null

  scss/dollar-variable-empty-line-before: null
